### ISSUE TITLE
The query speed of market, lend, and borrow pages is too slow (more than 60s)

### ISSUE THREAD

**Issue by DomFeng** [pledge-defi/Pledge-main#1]
recurring process：
website：https://v2.pledger.finance/BUSD
Click to query market, lend, and borrow

screenshot：
![image](https://user-images.githubusercontent.com/61138066/149444678-8a3c9edc-3175-45fa-88d2-d0d2da09d7f4.png)

**Comment by pswwwwww** [comment]
已解决
